api:
  dashboard: true
  insecure: true  # Set to false in production and use proper authentication

entryPoints:
  http:
    address: ":80"
  
  https:
    address: ":443"
  
  # Custom entrypoint for Prefect
  prefect:
    address: ":8000"

# Configure your providers
providers:
  file:
    directory: /etc/traefik/config
    watch: true
  docker:
    exposedByDefault: false
